### PR TITLE
Recognize non-ASCII punctuation chars

### LINKED ISSUE #53: Scanner should recognize non-ASCII punctuation chars
Hi stsewd, thank for your awesome rst parser!  

I found this parser works no so well when parse documentation written in CJK.
For example: ``:strong:`text`。`` (trailing with a Chinese full stop `。`, in Engish it is `.`) is a valid inline markup (OK for `rst2pseudoxml`), but can not be correctly recognize by tree-sitter-rst.

# How to reproduce

```
$ echo ':strong:`text`。' > example.rst
$ rst2pseudoxml example.rst
<document source="example.rst">
    <paragraph>
        <strong>
            text
        。
$ tree-sitter p example.rst
(document [0, 0] - [1, 0]
  (ERROR [0, 0] - [0, 8]
    (role [0, 0] - [0, 8]))
  (paragraph [0, 8] - [0, 17]))
example.rst        0.03 ms         607 bytes/ms (ERROR [0, 0] - [0, 8])
```

# How to fix

According to [Inline markup recognition rules](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#inline-markup-recognition-rules):

> Inline markup start-strings must start a text block or be immediately preceded by
> 
> * whitespace,
> * one of the ASCII characters - : / ' " < ( [ {
> * **or a similar non-ASCII punctuation character.** [18]
> 
> Inline markup end-strings must end a text block or be immediately followed by
> 
> * whitespace,
> * one of the ASCII characters - . , : ; ! ? \ / ' " ) ] } >
> * **or a similar non-ASCII punctuation character.** [19]

I have make a PR(#10) for this, but it is not a good fix.
Docutils provides [some regex](https://github.com/docutils/docutils/blob/master/docutils/docutils/utils/punctuation_chars.py) for matching these non-ASCII punctuation characters. According to my current understanding, matching them in `src/tree_sitter_rst/chars.c::is_{start,end}_char` should fix this issue.

### PR DESCRIPTION
**Pull request by SilverRainZ**
The `punctuation_chars.h` header file is auto-generated from `gen_punctuation_chars.py`.
I also add a test case "Unicode Punctuation Chars":

before:

```
  inline_markup:
    ✗ Unicode Punctuation Chars

1 failure:

correct / expected / unexpected

  1. Unicode Punctuation Chars:

    (document
      (paragraph)
      (paragraph)
      (paragraph)
      (paragraph))
      (paragraph
        (emphasis))
      (paragraph
        (emphasis)
        (strong))
      (paragraph
        (emphasis))
      (paragraph
        (emphasis)))
```

after:

```
  inline_markup:
    ✓ Unicode Punctuation Chars
```

Any comments are welcome.

Close #53.

### CODE REVIEW

**Comment by SilverRainZ** [comment]
@stsewd Can you please review it?

**Comment by stsewd** [comment]
@SilverRainZ thank you for opening this PR! I'll try to take a look at it this weekend or the next one (sorry, busy weeks). I just noticed that the Windows CI is failing with this change.

**Comment by SilverRainZ** [comment]
The Windows CI failed with a weird error message:

```
 scanner.c
D:\a\tree-sitter-rst\tree-sitter-rst\src\tree_sitter_rst\punctuation_chars.h(107,41): error C2059: syntax error: '}' [D:\a\tree-sitter-rst\tree-sitter-rst\build\tree_sitter_rst_binding.vcxproj]
  (compiling source file '../src/scanner.c')
```

I have checked L107 and there is nothing special, I have no idea for now.

```c
// ...
  L'\u201f',
};
const int32_t start_chars_range[][2] = {}; // <-- L107

const int32_t delim_chars[] = {
// ...

**Comment by SilverRainZ** [comment]
It seems that we should update the WASM binary after any changes, but I think it should be done with the maintainer.

B.T.W, the  `npm run wasm` is broken due to https://github.com/tree-sitter/tree-sitter/issues/3202.

**Review by stsewd — APPROVED** [review]
Thanks for this great contribution! I did some small edits and fixed the Windows build by not generating empty arrays (since the array was empty, when trying to access to the first element, it was probably pointing to invalid memory/values, and Windows didn't like that).

**Pull request merged**
